install.packages("zoo")
install.packages("plyr")
install.packages("dplyr")
install.packages("quantmod")
install.packages("ggplot2")
install.packages("reshape2")

install.packages("scales")
install.packages("openair")
library(zoo)
library(quantmod)
library(ggplot2)
library(reshape2)
library(plyr)
library(scales)
library(openair)
library(dplyr)